### ISSUE TITLE
Furniture clips through floor window, softlock occasionally 

### ISSUE THREAD

**Issue by Hexmy** [Test-Account666/LethalCompany-ShipWindows#13]
If you attempt to place furniture such as the terminal or cabinet while on a planet onto the window, the furniture will clip through the window and onto the ground. On some planets, (such as offense in my experience) once the furniture is down there, you just can't get it back up! If you try, it'll make the noise like it moved, but stay in the same position. And even worse, if you use the terminal while it's through the floor, you just get stuck there! (image provided, had to restart)
![image_2024-08-04_015544243](https://github.com/user-attachments/assets/b6e522e6-f2ef-4d39-a213-4ff151ce184c)

There's another issue open about how you just can't place stuff over the window, but it's apparent it goes a little further than that, so I made my own

**Comment by Test-Account666** [comment]
Should be fixed a long time ago, so I'll close this now
