### ISSUE TITLE
[Request] Wesley voice lines don't play during transit, landing, etc. when the ship has no windows

### ISSUE THREAD

**Issue by prototype464** [Test-Account666/LethalCompany-ShipWindows#5]
I noticed the Wesley lines (closing shutters, opening shutters, etc.) play even though we're on a fresh save and the ship currently has no windows. Likely a simple fix.

**Comment by Test-Account666** [comment]
Going to be fixed in 1.3.1.

Sorry, kinda forgot about this issue, so I didn't include it in 1.3.0...
