### ISSUE TITLE
[Request] Combine Wesley's transit voice lines or reduce their frequency in some way

### ISSUE THREAD

**Issue by prototype464** [Test-Account666/LethalCompany-ShipWindows#6]
My friends and I turned the Wesley lines off in the config because it gets irritatingly frequent when we move between moons often in our run. I'd like to propose an idea for a combined voiceline, something like "Alert. Closing shutters for transit.", or something along the lines of that. I don't think they're really even necessary overall considering the door doesn't even have voice lines, but that's probably just me. It's still a neat feature.

**Comment by Test-Account666** [comment]
The voice lines can be configured to only play when using the shutter switch.

Wouldn't that solve your issue?
